# Use the boky/postfix image as the base
FROM bokysan/postfix

# Set the necessary environment variables for your domain
ENV MAILNAME=${MAILNAME}
ENV MYNETWORKS=${MYNETWORKS}
ENV VIRTUAL_ALIAS_DOMAINS=${VIRTUAL_ALIAS_DOMAINS}
ENV VIRTUAL_ALIAS_MAPS=${VIRTUAL_ALIAS_MAPS}

# Set additional environment variables for further customization
ENV MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
ENV POSTFIX_SPF_SENDER_DOMAINS=${POSTFIX_SPF_SENDER_DOMAINS}
ENV POSTFIX_SPF_FAIL_SCORES=${POSTFIX_SPF_FAIL_SCORES}
ENV POSTFIX_DKIM_DOMAINS=${POSTFIX_DKIM_DOMAINS}
ENV POSTFIX_DKIM_SELECTOR=${POSTFIX_DKIM_SELECTOR}
ENV POSTFIX_DKIM_PRIVATE_KEY=${POSTFIX_DKIM_PRIVATE_KEY}
ENV POSTFIX_DMARC_QUARANTINE_SCORE=${POSTFIX_DMARC_QUARANTINE_SCORE}
ENV POSTFIX_DMARC_REJECT_SCORE=${POSTFIX_DMARC_REJECT_SCORE}

# Expose the necessary ports (optional)
EXPOSE 25 587
